services:
  express:
    build: 
      context: ./apps/express
      dockerfile: Dockerfile
    image: ollama-express
    ports: 
      - "3000:3000"
    depends_on:
      - ollama
  ollama:
    image: "ollama/ollama"
    volumes:
      - ollama:/root/.ollama
    ports: 
      - "11434:11434"

volumes:
  ollama: